import { solve } from '../day11/day11a'
import { readInput } from './day11a'

describe('day11b', () => {
    it('should solve', () => {
        expect(solve(readInput(), 1e6)).toEqual(650672493820)
    })
    it('should solve example', () => {
        expect(solve(`...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`, 10)).toEqual(1030)
    })
    it('should solve example', () => {
        expect(solve(`...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....`, 100)).toEqual(8410)
    })
})

