name: aoc2022

on:
  push:
    paths:
      - aoc2022/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Cargo
        run: sudo apt update && sudo apt install cargo

      - name: Test
        working-directory: ./aoc2022
        run: cargo test --verbose
