name: aoc2023

on:
  push:
    paths:
      - aoc2023/**

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
        working-directory: ./aoc2023

      - run: npm run build
        working-directory: ./aoc2023

      - run: npm run test
        working-directory: ./aoc2023

