name: main

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: ./aoc2022

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
